export const ARTIKEL_BLOG = [
  {
    "slug": "usaha-ramai-uang-ke-mana",
    "judul": "Usaha Ramai, Uang ke Mana?",
    "ringkasan": "Pesanan masuk terus, tapi uang terasa cepat habis. Mulai dengan melihat catatan uang masuk, uang keluar, dan pembayaran yang belum diterima.",
    "menitBaca": 3,
    "isi": "Seharian melayani pembeli, membungkus pesanan, lalu belanja lagi. Begitu toko tutup, uang yang tersisa terasa sedikit. Kalau begini, pertanyaan pertama yang bisa diperiksa adalah: hari ini uang masuk dari mana, lalu dipakai untuk apa?\n\nCatatan sederhana bisa jadi titik awal. Siapkan buku, catatan di ponsel, atau alat yang memang nyaman dipakai setiap hari.\n\n## Mulai dari satu hari yang lengkap\n\nTulis tanggal, keterangan, uang masuk, dan uang keluar. Masukkan pengeluaran kecil juga: kantong belanja, ongkos kirim yang ditanggung toko, atau parkir saat mengambil barang. [Catatan penjualan dan pengeluaran yang teratur membantu usaha melihat pergerakan uangnya](https://business.gov.au/guide/guide-to-managing-cash-flow).\n\nKalau ada uang usaha yang dipakai untuk kebutuhan pribadi, beri keterangan tersendiri. Begitu juga saat menambahkan uang pribadi ke usaha. Dengan begitu, asal dan tujuan uangnya masih bisa ditelusuri saat dibaca lagi.\n\n## Coba lihat contoh ini\n\nMisalnya, sebuah toko menerima pembayaran Rp500.000 hari ini. Lalu ada belanja barang Rp300.000, pembelian kemasan Rp25.000, dan ongkos antar Rp25.000.\n\nSelisih uang masuk dan keluar hari itu adalah Rp150.000. Angka ini belum menunjukkan laba usaha. Masih ada hal lain yang perlu diperiksa, seperti barang yang belum terjual dan biaya usaha untuk periode tersebut.\n\nContoh ini berguna untuk menjawab pertanyaan yang lebih kecil: berapa uang yang masuk dan keluar hari ini? Mulai dari jawaban yang bisa dicek dulu.\n\n## Cek pembayaran yang belum masuk\n\nPesanan selesai belum selalu berarti pembayarannya sudah diterima. Buat daftar singkat: pesanan apa, jumlah pembayaran, tanggal yang disepakati, dan apakah uangnya sudah masuk.\n\nUntuk penjualan lewat aplikasi, cocokkan catatan pesanan dengan dana yang benar-benar diterima. Jika jumlahnya berbeda, lihat rincian potongan dan jadwal pencairan pada layanan yang dipakai.\n\n## Tutup hari dengan mengecek catatan\n\nSebelum selesai bekerja, cocokkan catatan dengan uang tunai dan transaksi rekening yang digunakan untuk usaha. Tandai selisih yang belum jelas supaya bisa dicari kembali lewat bukti transaksi.\n\nBesok, lanjutkan cara yang sama. Setelah terkumpul beberapa hari, baca ulang: pengeluaran apa yang berulang? Pembayaran mana yang masih tertunda?\n\nLangkah pertama hari ini cukup jelas: catat seluruh transaksi sampai toko tutup, lalu cocokkan. Dari situ, pertanyaan “uangnya ke mana?” mulai punya jawaban yang bisa dilihat."
  },
  {
    "slug": "kalau-jualan-lagi-sepi",
    "judul": "Kalau Jualan Lagi Sepi",
    "ringkasan": "Sebelum mengganti harga atau menambah promosi, cari tahu dulu sepinya di bagian mana. Lalu coba satu perubahan kecil yang bisa diperiksa hasilnya.",
    "menitBaca": 3,
    "isi": "Saat jualan sepi, rasanya ingin mencoba semuanya sekaligus. Ganti foto, turunkan harga, tambah produk, lalu unggah promosi lebih sering. Tapi kalau semuanya berubah bersamaan, kita akan kesulitan melihat perubahan mana yang membantu.\n\nCoba mulai dengan satu pertanyaan: sepinya terjadi di bagian mana?\n\n## Lihat apa yang sebenarnya berkurang\n\nApakah makin sedikit orang yang datang atau melihat produk? Apakah pertanyaan masih masuk, tetapi pesanan berkurang? Atau pembeli lama belum kembali?\n\nCatat yang bisa dilihat dari usaha sendiri. Misalnya jumlah orang yang bertanya, pesanan yang selesai, dan pertanyaan yang sering muncul. Bandingkan hari yang serupa, seperti Sabtu dengan Sabtu, agar konteksnya lebih dekat.\n\nKalau belum punya catatan, mulailah hari ini. Jangan memaksakan kesimpulan dari ingatan yang samar atau satu hari yang kebetulan lengang.\n\n## Dengarkan pertanyaan pembeli\n\nSaat ada kesempatan berbicara, tanyakan hal yang ringan: “Ada informasi yang masih kurang jelas?” atau “Biasanya cari ukuran yang seperti apa?” Beri ruang untuk menjawab tanpa harus membeli.\n\n[Saran dan percakapan dengan pelanggan bisa membantu usaha memahami kebutuhan mereka](https://business.gov.au/marketing-and-advertising/do-market-research). Simpan inti jawabannya tanpa perlu mencatat informasi pribadi yang tidak dibutuhkan.\n\nPerhatikan juga percakapan yang sudah ada. Apakah banyak orang menanyakan harga, ukuran, lokasi, atau cara pesan? Pertanyaan yang berulang bisa menjadi petunjuk tentang informasi yang perlu diperjelas.\n\n## Coba satu perubahan kecil\n\nMisalnya, sebuah usaha kue sering menerima pertanyaan tentang jumlah kue dalam satu kotak. Pemiliknya bisa mencoba menambahkan tulisan “isi 6 buah” pada foto produk yang sudah ada.\n\nSelama percobaan, harga dan isi kotak tetap sama. Lalu catat apakah pertanyaan tentang isi kotak berkurang dan apakah pesanan berubah. Ini percobaan untuk belajar, tanpa janji bahwa penjualan pasti naik.\n\nPilih perubahan yang sesuai dengan masalah yang ditemukan. Kalau informasi jam buka sulit dicari, mulai dari memperjelas jam buka.\n\n## Tentukan kapan mau mengecek lagi\n\nTulis tanggal mulai dan tanggal untuk melihat hasilnya. Sesuaikan dengan kebiasaan jualan: usaha yang hanya buka akhir pekan perlu kesempatan untuk membandingkan beberapa akhir pekan.\n\nCatat juga hal lain yang terjadi, seperti hujan atau toko tutup lebih cepat. Hal-hal itu perlu dipertimbangkan saat membaca hasil.\n\nUntuk hari ini, pilih satu hal yang ingin diperjelas bagi pembeli. Kerjakan, catat, lalu cek kembali pada waktu yang sudah ditentukan. Kalau belum membantu, gunakan temuan itu untuk memilih percobaan berikutnya."
  },
  {
    "slug": "kapan-harus-berhenti-nambah-stok",
    "judul": "Kapan Harus Berhenti Nambah Stok?",
    "ringkasan": "Sebelum pesan barang lagi, lihat stok yang masih ada, barang yang benar-benar terjual, dan berapa lama pesanan baru akan tiba.",
    "menitBaca": 3,
    "isi": "Ada tawaran harga grosir, varian baru, atau kabar bahwa barang akan cepat habis. Rasanya sayang kalau tidak ikut pesan. Sebelum menambah stok, coba buka catatan penjualan dan lihat rak yang sudah terisi.\n\nKeputusan untuk pesan lagi bisa dimulai dari tiga hal: jumlah barang yang masih ada, jumlah yang terjual, dan waktu yang dibutuhkan pemasok untuk mengirim barang.\n\n## Hitung yang benar-benar tersedia\n\nPilih satu jenis barang dulu. Hitung jumlahnya, lalu pisahkan barang yang sudah dipesan pelanggan, rusak, atau tidak layak dijual. Catat juga barang pesanan ke pemasok yang belum sampai.\n\n[Catatan stok membantu usaha mengetahui barang yang tersedia dan kebutuhan pemesanan berikutnya](https://business.gov.au/products-and-services/inventory-management/manage-your-inventory). Periksa secara rutin agar angka di catatan sesuai dengan barang yang benar-benar ada.\n\nKalau ada beberapa ukuran atau warna, tulis terpisah. Jumlah keseluruhan bisa terlihat banyak, padahal ukuran yang sering diminta justru kosong.\n\n## Bandingkan dengan penjualan terakhir\n\nLihat berapa yang terjual dalam beberapa minggu terakhir. Apakah penjualannya relatif sama, sedang meningkat, atau hanya ramai saat ada acara tertentu?\n\nMisalnya, ada 30 tas siap dijual. Dalam masing-masing tiga minggu terakhir, terjual 5 tas. Kalau penjualan tetap sama, stok itu cukup untuk sekitar 6 minggu. Ini perkiraan sederhana; permintaan bisa berubah.\n\nAngka tersebut bisa dipakai untuk bertanya: apakah perlu pesan sekarang? Jawabannya masih perlu mempertimbangkan waktu pengiriman dan pesanan pelanggan yang sudah dikonfirmasi.\n\n## Cek alasan ingin membeli lagi\n\nCoba tulis alasan pemesanan dalam satu kalimat. “Warna hitam tinggal sedikit dan ada pesanan yang sudah masuk” lebih mudah diperiksa daripada “takut nanti kehabisan.”\n\nKalau alasan utamanya diskon pemasok, lihat kembali jumlah pembelian yang diminta. Barang yang lebih murah per buah tetap menambah jumlah barang yang harus disimpan dan dijual.\n\nUntuk varian yang belum pernah dijual, tanyakan apakah ada pilihan jumlah pesanan lebih kecil. Gunakan penjualan awal sebagai bahan belajar sebelum menentukan pesanan selanjutnya.\n\n## Beri jeda saat alasannya belum jelas\n\nJika jumlah stok belum diketahui atau barang lama jarang bergerak, selesaikan pemeriksaannya sebelum memutuskan pesanan tambahan. Cari tahu apakah masalahnya ada pada pilihan barang, informasi produk, atau permintaannya.\n\nHari ini, ambil satu barang yang paling sering dipesan ulang. Tulis stok tersedia, penjualan terakhir, pesanan yang belum datang, dan perkiraan waktu kirim pemasok.\n\nSetelah empat hal itu jelas, tentukan apakah perlu menambah, mengurangi jumlah pesanan, atau menunggu. Catat alasannya supaya bisa dibandingkan dengan keadaan saat pemeriksaan berikutnya."
  }
];
