const {test,after}=require('node:test');const assert=require('node:assert/strict');const React=require('react');const {loadSource,installDOM}=require('./helpers.cjs');const dom=installDOM();const {createRoot}=require('react-dom/client');const {act}=React;after(()=>dom.close());
async function mount(t,{reduced=false,saveData=false,fail=false,audio=false}={}){
 let loads=0,disposals=0,callback,audioDisposals=0,unlocks=0;const audioActive=[];window.AudioContext=audio?function(){}:undefined;const pauses=[];const media={matches:reduced,addEventListener:(_,cb)=>callback=cb,removeEventListener:()=>{}};window.matchMedia=()=>media;Object.defineProperty(navigator,'connection',{value:{saveData},configurable:true});
 const Scene=loadSource('src/components/CrowdScene.tsx',{'next/image':({priority,unoptimized,...props})=>React.createElement('img',props),'./ArrowIcon':()=>React.createElement('svg'),'@/lib/crowd-audio':{createCrowdAudio:report=>({unlock(){unlocks++;report(true)},setMuted(v){if(v)report(false)},setActive(v){audioActive.push(v)},frame(){},dispose(){audioDisposals++}})},'@/lib/illustrated-crowd-scene':{startIllustratedScene:(_,cb)=>{loads++;fail?cb.onError(Error('GPU')):cb.onReady();return{dispose:()=>disposals++,setPaused:v=>pauses.push(v)}}}}).default;
 const container=document.createElement('div');container.className='giveup-home';document.body.appendChild(container);const root=createRoot(container);await act(async()=>root.render(React.createElement(Scene)));t.after(async()=>{await act(async()=>root.unmount());container.remove()});
 return{container,root,pauses,audioActive,get unlocks(){return unlocks},get audioDisposals(){return audioDisposals},get loads(){return loads},get disposals(){return disposals},motion:async values=>act(async()=>{for(const value of values){media.matches=value;callback()}})};
}
test('automatic backdrop keeps layout footprint and has no animation controls',async t=>{const v=await mount(t);assert.equal(v.loads,1);assert.ok(v.container.querySelector('.bekal.crowd'));assert.equal(v.container.querySelector('.crowd-background').parentElement,v.container);assert.equal(v.container.querySelectorAll('button').length,0);assert.equal(v.container.querySelector('.crowd-background').getAttribute('aria-hidden'),'true');assert.equal(v.container.querySelector('.crowd-background__still').hidden,true)});
for(const mode of ['reduced','saveData'])test(`${mode} uses illustration without importing WebGL`,async t=>{const v=await mount(t,{[mode]:true});assert.equal(v.loads,0);assert.equal(v.container.querySelector('.crowd-background__still').hidden,false)});
test('GPU failure keeps automatic still fallback without retry controls',async t=>{const v=await mount(t,{fail:true});assert.equal(v.container.querySelector('.crowd-background__still').hidden,false);assert.equal(v.container.querySelectorAll('button').length,0)});
test('rapid preference toggles cannot start overlapping renderers',async t=>{const v=await mount(t,{reduced:true});await v.motion([false,true,false]);assert.equal(v.loads,1);await act(async()=>v.root.unmount());assert.equal(v.disposals,1)});
test('enabling reduced motion releases scene and turning off restores automatic playback',async t=>{const v=await mount(t);await v.motion([true]);assert.equal(v.disposals,1);assert.equal(v.container.querySelector('.crowd-background__still').hidden,false);await v.motion([false]);assert.equal(v.loads,2)});

test('supported audio adds only one accessible sound control and cleans up',async t=>{const v=await mount(t,{audio:true});const button=v.container.querySelector('button');assert.equal(v.container.querySelectorAll('button').length,1);assert.equal(button.className,'crowd-sound');assert.equal(button.getAttribute('aria-pressed'),'false');assert.ok(!button.closest('[aria-hidden="true"]'));document.dispatchEvent(new window.Event('pointerdown'));assert.equal(v.unlocks,0);await act(async()=>button.click());assert.equal(v.unlocks,0);assert.equal(button.getAttribute('aria-pressed'),'false');const props=button[Object.keys(button).find(k=>k.startsWith('__reactProps'))];await act(async()=>props.onClick({nativeEvent:{isTrusted:true}}));assert.equal(v.unlocks,1);assert.equal(button.getAttribute('aria-pressed'),'true');await v.motion([true]);assert.equal(v.container.querySelectorAll('button').length,0);assert.equal(v.audioActive.at(-1),false);await act(async()=>v.root.unmount());assert.equal(v.audioDisposals,1)});
