const {test,after}=require('node:test');const assert=require('node:assert/strict');const React=require('react');const {loadSource,installDOM}=require('./helpers.cjs');const dom=installDOM();const {createRoot}=require('react-dom/client');const {act}=React;after(()=>dom.close());
async function mount(t,{reduced=false,saveData=false,fail=false,audio=false}={}){
 let loads=0,disposals=0,callback,audioLoads=0,contexts=0;window.AudioContext=audio?function(){contexts++;throw Error("Unexpected audio context")}:undefined;const pauses=[];const media={matches:reduced,addEventListener:(_,cb)=>callback=cb,removeEventListener:()=>{}};window.matchMedia=()=>media;Object.defineProperty(navigator,'connection',{value:{saveData},configurable:true});
 const Scene=loadSource('src/components/CrowdScene.tsx',{'next/image':({priority,unoptimized,...props})=>React.createElement('img',props),'./ArrowIcon':()=>React.createElement('svg'),'@/lib/crowd-audio':{createCrowdAudio:()=>{audioLoads++;throw Error('Unexpected audio engine')}},'@/lib/illustrated-crowd-scene':{startIllustratedScene:(_,cb)=>{loads++;fail?cb.onError(Error('GPU')):cb.onReady();return{dispose:()=>disposals++,setPaused:v=>pauses.push(v)}}}}).default;
 const container=document.createElement('div');container.className='giveup-home';document.body.appendChild(container);const root=createRoot(container);await act(async()=>root.render(React.createElement(Scene)));t.after(async()=>{await act(async()=>root.unmount());container.remove()});
 return{container,root,pauses,get audioLoads(){return audioLoads},get contexts(){return contexts},get loads(){return loads},get disposals(){return disposals},motion:async values=>act(async()=>{for(const value of values){media.matches=value;callback()}})};
}
test('automatic backdrop keeps layout footprint and has no animation controls',async t=>{const v=await mount(t);assert.equal(v.loads,1);assert.ok(v.container.querySelector('.bekal.crowd'));assert.equal(v.container.querySelector('.crowd-background').parentElement,v.container);assert.equal(v.container.querySelectorAll('button').length,0);assert.equal(v.container.querySelector('.crowd-background').getAttribute('aria-hidden'),'true');assert.equal(v.container.querySelector('.crowd-background__still').hidden,true)});
for(const mode of ['reduced','saveData'])test(`${mode} uses illustration without importing WebGL`,async t=>{const v=await mount(t,{[mode]:true});assert.equal(v.loads,0);assert.equal(v.container.querySelector('.crowd-background__still').hidden,false)});
test('GPU failure keeps automatic still fallback without retry controls',async t=>{const v=await mount(t,{fail:true});assert.equal(v.container.querySelector('.crowd-background__still').hidden,false);assert.equal(v.container.querySelectorAll('button').length,0)});
test('rapid preference toggles cannot start overlapping renderers',async t=>{const v=await mount(t,{reduced:true});await v.motion([false,true,false]);assert.equal(v.loads,1);await act(async()=>v.root.unmount());assert.equal(v.disposals,1)});
test('enabling reduced motion releases scene and turning off restores automatic playback',async t=>{const v=await mount(t);await v.motion([true]);assert.equal(v.disposals,1);assert.equal(v.container.querySelector('.crowd-background__still').hidden,false);await v.motion([false]);assert.equal(v.loads,2)});

test('homepage stays silent after interaction even when Web Audio is supported',async t=>{const v=await mount(t,{audio:true});assert.equal(v.container.querySelectorAll('button').length,0);await act(async()=>{document.dispatchEvent(new window.Event('pointerdown'));document.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Enter'}));v.container.click()});assert.equal(v.audioLoads,0);assert.equal(v.contexts,0);assert.equal(v.loads,1);await v.motion([true,false]);assert.equal(v.audioLoads,0);assert.equal(v.contexts,0);assert.equal(v.container.querySelectorAll('button').length,0)});
