const {test}=require('node:test');const assert=require('node:assert/strict');const {loadSource,installDOM}=require('./helpers.cjs');
const load=()=>loadSource('src/lib/crowd-audio.ts',{'./crowd-story':loadSource('src/lib/crowd-story.ts')});
function fixture(t,{reject=false,stored=null}={}){
 const dom=installDOM();t.after(()=>dom.close());let count=0;const contexts=[];const old=Object.getOwnPropertyDescriptor(globalThis,'localStorage');Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>stored,setItem:(_,v)=>stored=v}});t.after(()=>{if(old)Object.defineProperty(globalThis,'localStorage',old);else delete globalThis.localStorage});
 const param=()=>({value:0,cancelScheduledValues(){},setTargetAtTime(v){this.value=v},setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v},exponentialRampToValueAtTime(v){this.value=v}});
 class Context{constructor(){count++;this.state='suspended';this.currentTime=0;this.sampleRate=8000;this.destination={};this.sources=[];this.nodes=[];contexts.push(this)}node(){const n={connect(){},disconnect(){this.disconnected=true},gain:param(),frequency:param()};this.nodes.push(n);return n}createGain(){return this.node()}createBiquadFilter(){return this.node()}createBuffer(_,length){return{length,copyToChannel(){}}}createBufferSource(){const n=this.node();n.start=function(){this.started=true};n.stop=function(){this.stopped=true};this.sources.push(n);return n}resume(){if(reject)return Promise.reject(Error('blocked'));this.state='running';this.onstatechange?.();return Promise.resolve()}suspend(){this.state='suspended';this.onstatechange?.();return Promise.resolve()}close(){this.closed=true;this.state='closed';return Promise.resolve()}}
 window.AudioContext=Context;const states=[];const handle=load().createCrowdAudio(v=>states.push(v));t.after(()=>handle.dispose());return{handle,states,contexts,get count(){return count},get stored(){return stored},async settle(){await Promise.resolve();await Promise.resolve()}};
}
test('original noise is deterministic, bounded and non-silent',()=>{const {makeCrowdNoise}=load();const a=makeCrowdNoise(48000);assert.deepEqual(a,makeCrowdNoise(48000));assert.ok(a.some(x=>Math.abs(x)>.1));assert.ok(a.every(x=>Number.isFinite(x)&&Math.abs(x)<1));});
test('no context before gesture; repeated unlocks reuse one context',async t=>{const f=fixture(t);f.handle.setActive(true);assert.equal(f.count,0);f.handle.unlock();f.handle.unlock();await f.settle();assert.equal(f.count,1);assert.equal(f.states.at(-1),true)});
test('footsteps use scene clock, pause suspends and resume avoids catch-up bursts',async t=>{const f=fixture(t);f.handle.setActive(true);f.handle.unlock();await f.settle();const c=f.contexts[0];for(let i=0;i<250;i++){c.currentTime=i*.04;f.handle.frame(i*.04)}assert.ok(c.sources.length>3);assert.ok(c.sources.length<75);f.handle.setActive(false);assert.equal(c.state,'suspended');assert.equal(f.states.at(-1),false);const n=c.sources.length;f.handle.frame(14);assert.equal(c.sources.length,n);f.handle.setActive(true);await f.settle();f.handle.frame(14);assert.equal(c.sources.length,n)});
test('persisted mute blocks automatic unlock, explicit unmute enables sound',async t=>{const f=fixture(t,{stored:'1'});f.handle.setActive(true);f.handle.unlock();assert.equal(f.count,0);f.handle.setMuted(false);f.handle.unlock();await f.settle();assert.equal(f.states.at(-1),true);assert.equal(f.stored,'0');f.handle.setMuted(true);assert.equal(f.states.at(-1),false);assert.equal(f.contexts[0].state,'suspended');assert.equal(f.stored,'1')});
test('rejected autoplay resume is contained and disposal is idempotent',async t=>{const f=fixture(t,{reject:true});f.handle.setActive(true);f.handle.unlock();await f.settle();assert.equal(f.states.includes(true),false);f.handle.dispose();f.handle.dispose();assert.equal(f.contexts[0].closed,true);assert.ok(f.contexts[0].sources.every(s=>s.stopped));assert.ok(f.contexts[0].nodes.every(n=>n.disconnected));f.handle.unlock();assert.equal(f.count,1)});
test('unavailable Web Audio is a silent no-op',t=>{const dom=installDOM();t.after(()=>dom.close());const h=load().createCrowdAudio(()=>{});h.setActive(true);h.unlock();h.frame(1);h.dispose()});
