const {test}=require('node:test');const assert=require('node:assert/strict');const THREE=require('three');const {loadSource,installDOM}=require('./helpers.cjs');
function runtime(t,{reduced=false,fail=false,width=1200,height=760}={}){const dom=installDOM();const media={matches:reduced,addEventListener(){},removeEventListener(){}};window.matchMedia=()=>media;Object.defineProperty(window,'innerWidth',{value:width,configurable:true});Object.defineProperty(window,'devicePixelRatio',{value:3,configurable:true});let id=0,now=1000;const pending=new Map();const originals=new Map();for(const [key,value]of Object.entries({requestAnimationFrame:f=>{pending.set(++id,f);return id},cancelAnimationFrame:i=>pending.delete(i),ResizeObserver:class{observe(){}disconnect(){}}})){originals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{value,writable:true,configurable:true});}
const renders=[],statuses=[],cameras=[];let renderedScene;let renderer;class Renderer{constructor(){if(fail)throw Error('GPU');this.domElement=document.createElement('canvas');renderer=this;this.disposals=0}setClearColor(){}setPixelRatio(value){this.dpr=value}setSize(){}render(s,c){s.updateMatrixWorld(true);c.updateMatrixWorld(true);cameras.push(c.clone());renderedScene=s;renders.push(s.children[0].children[0].position.y)}dispose(){this.disposals++}}
const old=loadSource('src/lib/crowd-model.ts');const model=loadSource('src/lib/illustrated-crowd-model.ts',{'./illustrated-rock':loadSource('src/lib/illustrated-rock.ts'),'./ink-shadow':loadSource('src/lib/ink-shadow.ts'),'./crowd-story':loadSource('src/lib/crowd-story.ts')});const {startIllustratedScene}=loadSource('src/lib/illustrated-crowd-scene.ts',{three:{...THREE,WebGLRenderer:Renderer},'./illustrated-crowd-model':model,'./crowd-camera':loadSource('src/lib/crowd-camera.ts',{'./crowd-story':loadSource('src/lib/crowd-story.ts')})});const host=document.createElement('div');Object.defineProperty(host,'clientWidth',{value:width});Object.defineProperty(host,'clientHeight',{value:height});const handle=startIllustratedScene(host,{onReady:()=>statuses.push('ready'),onError:()=>statuses.push('failed')});t.after(()=>{handle.dispose();for(const[k,v]of originals){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k]}dom.close()});return{host,handle,statuses,renders,cameras,get scene(){return renderedScene},get renderer(){return renderer},get frames(){return pending.size},tick(n=1){for(let i=0;i<n;i++){now+=16;const jobs=[...pending.values()];pending.clear();jobs.forEach(f=>f(now))}}};}
test('background auto-starts and visibly lifts without any help API or clicks',t=>{const v=runtime(t);assert.deepEqual(v.statuses,['ready']);assert.equal(v.handle.help,undefined);const base=v.renders[0];v.tick(850);assert.ok(v.renders.at(-1)>base+.47)});
test('hidden tabs and explicit intersection pause stop RAF and do not catch up',t=>{const v=runtime(t);v.tick(100);v.handle.setPaused(true);const n=v.renders.length;v.tick(400);assert.equal(v.renders.length,n);assert.equal(v.frames,0);v.handle.setPaused(false);v.tick();assert.equal(v.renders.length,n+1);Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new window.Event('visibilitychange'));assert.equal(v.frames,0)});
test('reduced motion renders one stable frame with no loop',t=>{const v=runtime(t,{reduced:true});assert.equal(v.frames,0);v.tick(100);assert.equal(v.renders.length,1)});
test('context loss cleans canvas and RAF exactly once',t=>{const v=runtime(t);v.renderer.domElement.dispatchEvent(new window.Event('webglcontextlost',{cancelable:true}));assert.equal(v.frames,0);assert.equal(v.host.children.length,0);assert.equal(v.renderer.disposals,1);v.handle.dispose();assert.equal(v.renderer.disposals,1);assert.deepEqual(v.statuses,['ready','failed'])});
test('GPU failure reports the illustration fallback',t=>{const v=runtime(t,{fail:true});assert.deepEqual(v.statuses,['failed']);assert.equal(v.frames,0);assert.equal(v.host.children.length,0)});
for(const [width,height] of [[390,844],[320,700],[1200,760]])test(`entire dispersed world stays between clipping planes at ${width}x${height}`,t=>{const v=runtime(t,{width,height});const camera=v.cameras.at(-1);camera.updateMatrixWorld(true);const p=new THREE.Vector3();v.scene.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).applyMatrix4(camera.matrixWorldInverse);assert.ok(-p.z>camera.near&&-p.z<camera.far,`${o.name} depth ${-p.z} beyond ${camera.far}`)}})});
test('dense scene caps desktop render cadence and mobile DPR',t=>{const v=runtime(t,{width:390,height:844});assert.equal(v.renderer.dpr,1);v.tick(120);assert.ok(v.renders.length<=62&&v.renders.length>=55)});
