const {test}=require('node:test');const assert=require('node:assert/strict');const THREE=require('three');const fs=require('fs');const crypto=require('crypto');const {loadSource}=require('./helpers.cjs');const {createIllustratedCrowd,poseIllustratedCrowd}=loadSource('src/lib/illustrated-crowd-model.ts',{'./illustrated-rock':loadSource('src/lib/illustrated-rock.ts'),'./ink-shadow':loadSource('src/lib/ink-shadow.ts'),'./crowd-story':loadSource('src/lib/crowd-story.ts')});
test('original illustration uses thirty-six continuous flat silhouettes and an actual dimensional rock',()=>{const m=createIllustratedCrowd();assert.equal(m.actors.length,36);m.root.traverse(o=>{if(o.isMesh)assert.ok(o.material.isMeshBasicMaterial||o.material.isShaderMaterial&&o.name.includes('shadow'))});m.root.updateMatrixWorld(true);const size=new THREE.Box3().setFromObject(m.rock).getSize(new THREE.Vector3());assert.ok(size.z>2);for(const a of m.actors){assert.equal(a.parts.length,2);assert.ok(a.parts[0].geometry.attributes.position.count>100)}m.dispose()});
test('ambient loop clearly lifts the boulder while preserving finite bounded silhouette geometry',()=>{const m=createIllustratedCrowd();poseIllustratedCrowd(m,0);const base=m.rock.position.y;poseIllustratedCrowd(m,13.5);assert.ok(m.rock.position.y>base+.47);for(let i=0;i<80;i++){poseIllustratedCrowd(m,i*.11);m.actors.forEach(a=>a.parts.forEach(p=>assert.ok(Array.from(p.geometry.attributes.position.array).every(Number.isFinite))))}poseIllustratedCrowd(m,24);assert.ok(Math.abs(m.rock.position.y-base)<1e-8);m.dispose()});
test('reduced motion is stable and disposal is idempotent',()=>{const m=createIllustratedCrowd();poseIllustratedCrowd(m,0,true);const a=Array.from(m.actors[0].parts[0].geometry.attributes.position.array);poseIllustratedCrowd(m,900,true);assert.deepEqual(Array.from(m.actors[0].parts[0].geometry.attributes.position.array),a);m.dispose();m.dispose()});
test('accepted title and font imports stay byte-identical while navigation and below-hero blog evolve',()=>{const files={'src/components/DontGiveUpTitle.tsx':'a9aae8662961de2668e2b23a95c32611445975c70234a7afb2cca644098c79be','src/app/layout.tsx':'908527a6748ca12d484b596b9a3b0abb91efd718a33d9326a8f4358e6790649b'};for(const [path,expected] of Object.entries(files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),expected,path)});
test('all accepted foreground CSS is preserved before the animation-only additions',()=>{const css=fs.readFileSync('src/app/interface.css','utf8');const marker='\n/* Animation-only background layer; accepted foreground dimensions stay intact. */';const prefix=css.slice(0,css.indexOf(marker));assert.equal(crypto.createHash('sha256').update(prefix).digest('hex'),'bcdf2c9335be2f138a88f12043d6820d12491bbd3695fed827dd27efabf224a4');assert.match(css,/\.crowd-background \{[^}]*pointer-events:none/)});
test('both hands of every illustrated supporter stay beneath the rock footprint throughout the lift',()=>{
 const m=createIllustratedCrowd();const polygon=loadSource('src/lib/illustrated-rock.ts').ROCK_FOOTPRINT;
 function inside(x,z){let yes=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const [xi,zi]=polygon[i],[xj,zj]=polygon[j];if((zi>z)!=(zj>z)&&x<(xj-xi)*(z-zi)/(zj-zi)+xi)yes=!yes;}return yes;}
 for(const time of [0,5.4,7,9.5,11.5,13.5,16.5]){poseIllustratedCrowd(m,time);m.root.updateMatrixWorld(true);for(const a of m.actors){if(a.support<.999)continue;const p=a.parts[0].geometry.attributes.position;for(const sign of [-1,1]){let top=null;for(let i=0;i<p.count;i++){const point=new THREE.Vector3().fromBufferAttribute(p,i);if(point.x*sign>.4&&(!top||point.y>top.y))top=point;}top.applyMatrix4(a.root.matrixWorld);assert.ok(Math.abs(top.y-(m.rock.position.y+Math.tan(m.rock.rotation.z)*top.x))<.05,'fingertip remains in contact band');assert.ok(inside(top.x/1.35,top.z/1.25),'fingertip stays inside underside polygon');}}}m.dispose();
});
test('approaching helpers articulate alternating legs instead of sliding rigidly',()=>{const m=createIllustratedCrowd();poseIllustratedCrowd(m,3);const a=m.actors[3],first=Array.from(a.parts[0].geometry.attributes.position.array),origin=a.root.position.clone();poseIllustratedCrowd(m,3.3);const next=Array.from(a.parts[0].geometry.attributes.position.array);let max=0;for(let i=0;i<first.length;i+=3)if(first[i+1]<.6)max=Math.max(max,Math.abs(first[i+1]-next[i+1]));assert.ok(max>.04);assert.ok(origin.distanceTo(a.root.position)>.2);assert.equal(a.support,0);m.dispose()});
test('changing arm posture keeps indices valid and geometry finite',()=>{const m=createIllustratedCrowd();for(let t=4;t<6;t+=.035){poseIllustratedCrowd(m,t);for(const a of m.actors)for(const p of a.parts){assert.ok(Array.from(p.geometry.index.array).every(i=>i<p.geometry.attributes.position.count));assert.ok(Array.from(p.geometry.attributes.position.array).every(Number.isFinite));}}m.dispose()});
test('distant walkers do not stretch their faces when supporters lift the rock',()=>{const m=createIllustratedCrowd();poseIllustratedCrowd(m,0);const a=m.actors[20],p=a.parts[0].geometry.attributes.position,original=Array.from(p.array);poseIllustratedCrowd(m,13.5);const after=a.parts[0].geometry.attributes.position.array;for(let i=0;i<original.length;i+=3)if(original[i+1]>1.5)assert.ok(Math.abs(original[i+1]-after[i+1])<1e-6);assert.equal(a.eyes.position.y,1.77);m.dispose()});
test('walk start eases in without snapping a raised foot into place',()=>{const m=createIllustratedCrowd();poseIllustratedCrowd(m,.99);const before=Array.from(m.actors[3].parts[0].geometry.attributes.position.array);poseIllustratedCrowd(m,1.01);const after=m.actors[3].parts[0].geometry.attributes.position.array;assert.ok(Math.max(...before.map((v,i)=>Math.abs(v-after[i])))<.01);m.dispose()});
test('reference-driven palette is mostly paper and gray with scarce butter accents and charcoal details',()=>{const m=createIllustratedCrowd();const colors=m.actors.map(a=>a.root.children.find(o=>o.name==='flat-illustrated-silhouette').material.color.getHexString());assert.equal(colors.filter(c=>['f0d47e','eedfa8'].includes(c)).length,4);let hair=0,hatch=false,contour=false;m.root.traverse(o=>{if(o.name==='charcoal-hair')hair++;if(o.name==='authored-boulder-hatching')hatch=o.geometry.attributes.position.count>100;if(o.name==='continuous-boulder-ink-contour')contour=true});assert.equal(hair,18);assert.ok(hatch&&contour);m.dispose()});
test('supporters have distinct heights and a genuinely staggered-depth cluster',()=>{const m=createIllustratedCrowd();poseIllustratedCrowd(m,13.5);const a=m.actors.filter(a=>a.support>.99);assert.equal(a.length,18);assert.ok(new Set(a.map(a=>a.root.scale.y)).size>=5);assert.ok(Math.max(...a.map(a=>a.root.position.z))-Math.min(...a.map(a=>a.root.position.z))>.9);m.dispose()});
test('36-person world reuses resources and preallocated buffers within a bounded geometry budget',()=>{const m=createIllustratedCrowd();const buffers=m.actors.flatMap(a=>a.parts.map(p=>[p.geometry.attributes.position.array,p.geometry.index.array]));let meshes=0,triangles=0;const geometries=new Set(),materials=new Set();m.root.traverse(o=>{if(!o.isMesh)return;meshes++;triangles+=Math.min(o.geometry.index?.count??o.geometry.attributes.position.count,o.geometry.drawRange.count)/3;geometries.add(o.geometry);materials.add(o.material)});assert.ok(meshes<=330,`${meshes} meshes`);assert.ok(triangles<32000,`${triangles} triangles`);assert.ok(materials.size<15,`${materials.size} materials`);for(let t=0;t<24;t+=.3)poseIllustratedCrowd(m,t);const after=m.actors.flatMap(a=>a.parts.map(p=>[p.geometry.attributes.position.array,p.geometry.index.array]));buffers.forEach((pair,i)=>{assert.equal(pair[0],after[i][0]);assert.equal(pair[1],after[i][1]);});const count=new Map([...geometries,...materials].map(r=>[r,0]));for(const r of count.keys())r.addEventListener('dispose',()=>count.set(r,count.get(r)+1));m.dispose();m.dispose();assert.ok([...count.values()].every(n=>n===1))});
test('rock and all36 people have ground-aligned analytic soft shadows that follow motion',()=>{const m=createIllustratedCrowd();poseIllustratedCrowd(m,0);const first=m.actors[3].shadow.position.clone(),scale=m.rockShadow.scale.x;assert.equal(m.actors.filter(a=>a.shadow.children[0].material.isShaderMaterial).length,36);assert.match(m.rockShadowMaterial.fragmentShader,/exp\(-r\*4\.2\)/);poseIllustratedCrowd(m,13.5);assert.ok(m.rockShadow.scale.x>scale);assert.ok(m.rockShadowMaterial.uniforms.strength.value>.15);assert.ok(m.actors[3].shadow.position.distanceTo(first)>1);for(const a of m.actors){assert.equal(a.shadow.position.y,.003);assert.ok(Math.abs(a.shadow.position.x-a.root.position.x)<1e-7);assert.ok(Math.abs(a.shadow.position.z-a.root.position.z)<1e-7)}m.dispose()});
test('walking feet stay close to the ground and contact shadows are centered under people',()=>{const m=createIllustratedCrowd();for(let t=0;t<24;t+=.37){poseIllustratedCrowd(m,t);m.root.updateMatrixWorld(true);for(const a of m.actors){const g=a.parts[0].geometry,p=new THREE.Vector3();let min=Infinity;for(let k=0;k<g.drawRange.count;k++){p.fromBufferAttribute(g.attributes.position,g.index.array[k]).applyMatrix4(a.root.matrixWorld);min=Math.min(min,p.y);}assert.ok(min>-.005&&min<.025,`${a.role} minY ${min} at ${t}`);assert.equal(a.shadow.position.x,a.root.position.x);assert.equal(a.shadow.position.z,a.root.position.z);}}m.dispose()});

test('accepted hero content and text-only CTA markup stay byte-identical alongside the separate blog section',()=>{const page=fs.readFileSync('src/app/page.tsx','utf8');const hero=page.match(/<main id="isi" className="giveup-main">[\s\S]*?<\/main>/)[0];assert.equal(crypto.createHash('sha256').update(hero).digest('hex'),'411b3388d66960eeae2a86855d71a7f7689b09ae53a73277cb3ed1a375421a09')});
